# Generated by Django 3.2.8 on 2022-02-22 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='club',
            name='mission_statement',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
