# Generated by Django 4.0.3 on 2022-03-04 01:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_club'),
    ]

    operations = [
        migrations.CreateModel(
            name='JoinedClub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clubName', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blogs.club')),
                ('userID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
